spring:
  profiles:
    default: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/open_ticket
    username: root
    password: '0000'

  jpa:
    hibernate:
      ddl-auto: none
---
spring:
  config:
    activate:
      on-profile: local

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: true
